# Site wide configuration

title: Christian Häusler
locale: en-US
description: About software architecture and security in the cloud
logo: images/site-logo.png

# Theming
remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/skins/dark.css"

# Site owner
author:
  name: Christian Häusler
  picture: images/christian.jpg
  email: haeusler.christian@mac.com
  links:
    - &twitter
      title: Twitter
      url: http://twitter.com/corvus_ch
      icon: fab fa-twitter-square
    - &linkedin
      title: Linkedin
      url: http://linkedin.com/in/christianhaeusler
      icon: fab fa-linkedin
    - &github
      title: GitHub
      url: http://github.com/corvus-ch
      icon: fab fa-github-square

# Comments
disqus:
  shortname: corvus-ch

# Footer Links
footer_links:
  - *twitter
  - *linkedin
  - *github
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

# Front Matter Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
